version: '3.4'

services:
  user-api:
    build: user-api
    container_name: user-api
    env_file: .env
    ports:
      - 3001:3000
    volumes: 
      - ./user-api/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - postgres
    stdin_open: true

      
  postgres:
    image: postgres
    env_file: .env
    ports: 
      - 5432:5432


